# Generated by Django 2.1.7 on 2020-05-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='row_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Row position'),
        ),
    ]
